version: 2
default:
  outputs:
    dev:
      account: "{{ env_var('DBT_ACCOUNT') }}"
      user: "{{ env_var('DBT_USER') }}"
      private_key_path: "{{ env_var('DBT_KEY_FILE') }}"
      private_key_passphrase: "{{ env_var('DBT_KEY_PASSPHRASE') }}"
      role: "{{ env_var('DBT_ROLE') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 32
      type: snowflake
      warehouse: direct_query
  target: dev
